//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighborhood
    {
        public Neighborhood()
        {
            this.Houses = new HashSet<House>();
        }
    
        public int NeighborhoodID { get; set; }
        public string Name { get; set; }
        public string URLName { get; set; }
        public string AdminEmail { get; set; }
        public string AdminPassPhrase { get; set; }
        public string AdminUserName { get; set; }
    
        public virtual ICollection<House> Houses { get; set; }
    }
}
