//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int OptionID { get; set; }
        public string Value { get; set; }
        public int NeighborhoodID { get; set; }
        public int OptionTypeID { get; set; }
    
        public virtual Neighborhood Neighborhood { get; set; }
        public virtual OptionType OptionType { get; set; }
    }
}
