//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int VisitID { get; set; }
        public int HouseID { get; set; }
        public int ResponseID { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual House House { get; set; }
        public virtual Respons Respons { get; set; }
    }
}
